name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Build Docker Image
        run: docker build -t yolo-detection .

      - name: Push Docker Image to AWS ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin <account_id>.dkr.ecr.us-east-1.amazonaws.com
          docker tag yolo-detection:latest <account_id>.dkr.ecr.us-east-1.amazonaws.com/yolo-detection:latest
          docker push <account_id>.dkr.ecr.us-east-1.amazonaws.com/yolo-detection:latest

      - name: Deploy Lambda
        run: |
          aws lambda update-function-code --function-name cnn-model-retrain --image-uri <account_id>.dkr.ecr.us-east-1.amazonaws.com/yolo-detection:latest
